// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GatewayInfo struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip                   []byte   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Name                 []byte   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Area                 []byte   `protobuf:"bytes,4,opt,name=area,proto3" json:"area,omitempty"`
	Status               uint32   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	UpdateTime           int64    `protobuf:"varint,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	CreateTime           int64    `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GatewayInfo) Reset()         { *m = GatewayInfo{} }
func (m *GatewayInfo) String() string { return proto.CompactTextString(m) }
func (*GatewayInfo) ProtoMessage()    {}
func (*GatewayInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{0}
}

func (m *GatewayInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatewayInfo.Unmarshal(m, b)
}
func (m *GatewayInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatewayInfo.Marshal(b, m, deterministic)
}
func (m *GatewayInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatewayInfo.Merge(m, src)
}
func (m *GatewayInfo) XXX_Size() int {
	return xxx_messageInfo_GatewayInfo.Size(m)
}
func (m *GatewayInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GatewayInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GatewayInfo proto.InternalMessageInfo

func (m *GatewayInfo) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GatewayInfo) GetIp() []byte {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *GatewayInfo) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *GatewayInfo) GetArea() []byte {
	if m != nil {
		return m.Area
	}
	return nil
}

func (m *GatewayInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GatewayInfo) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *GatewayInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type GatewayHeart struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GatewayId            uint32   `protobuf:"varint,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Status               uint32   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	UpdateTime           int64    `protobuf:"varint,4,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	CreateTime           int64    `protobuf:"varint,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GatewayHeart) Reset()         { *m = GatewayHeart{} }
func (m *GatewayHeart) String() string { return proto.CompactTextString(m) }
func (*GatewayHeart) ProtoMessage()    {}
func (*GatewayHeart) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{1}
}

func (m *GatewayHeart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatewayHeart.Unmarshal(m, b)
}
func (m *GatewayHeart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatewayHeart.Marshal(b, m, deterministic)
}
func (m *GatewayHeart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatewayHeart.Merge(m, src)
}
func (m *GatewayHeart) XXX_Size() int {
	return xxx_messageInfo_GatewayHeart.Size(m)
}
func (m *GatewayHeart) XXX_DiscardUnknown() {
	xxx_messageInfo_GatewayHeart.DiscardUnknown(m)
}

var xxx_messageInfo_GatewayHeart proto.InternalMessageInfo

func (m *GatewayHeart) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GatewayHeart) GetGatewayId() uint32 {
	if m != nil {
		return m.GatewayId
	}
	return 0
}

func (m *GatewayHeart) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GatewayHeart) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *GatewayHeart) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func init() {
	proto.RegisterType((*GatewayInfo)(nil), "models.gateway_info")
	proto.RegisterType((*GatewayHeart)(nil), "models.gateway_heart")
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor_f1a937782ebbded5) }

var fileDescriptor_f1a937782ebbded5 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xb1, 0x4e, 0x04, 0x21,
	0x10, 0x86, 0x03, 0xec, 0x61, 0x1c, 0x6f, 0x2d, 0x28, 0x0c, 0x8d, 0x71, 0x73, 0xd5, 0x56, 0x36,
	0x3e, 0x85, 0x2d, 0xb1, 0xdf, 0x8c, 0x32, 0x2a, 0x89, 0x1c, 0x84, 0xe5, 0x62, 0x7c, 0x13, 0x1f,
	0xc3, 0x47, 0x34, 0xc0, 0x66, 0xb3, 0xb1, 0xf0, 0xba, 0x99, 0x8f, 0x3f, 0xe4, 0xfb, 0x07, 0xfa,
	0x37, 0xcc, 0xf4, 0x89, 0x5f, 0xf7, 0x31, 0x85, 0x1c, 0x94, 0xf4, 0xc1, 0xd2, 0xc7, 0x7c, 0xf8,
	0x61, 0xb0, 0x5f, 0x5e, 0x26, 0x77, 0x7c, 0x0d, 0xea, 0x1a, 0xb8, 0xb3, 0x9a, 0x0d, 0x6c, 0xec,
	0x0d, 0x77, 0xb6, 0xee, 0x51, 0xf3, 0x81, 0x8d, 0x7b, 0xc3, 0x5d, 0x54, 0x0a, 0xba, 0x23, 0x7a,
	0xd2, 0xa2, 0x92, 0x3a, 0x17, 0x86, 0x89, 0x50, 0x77, 0x8d, 0x95, 0x59, 0xdd, 0x80, 0x9c, 0x33,
	0xe6, 0xd3, 0xac, 0x77, 0xf5, 0xaf, 0x65, 0x53, 0x77, 0x70, 0x75, 0x8a, 0x16, 0x33, 0x4d, 0xd9,
	0x79, 0xd2, 0x72, 0x60, 0xa3, 0x30, 0xd0, 0xd0, 0x93, 0xf3, 0x54, 0x02, 0x2f, 0x89, 0xd6, 0xc0,
	0x45, 0x0b, 0x34, 0x54, 0x02, 0x87, 0x6f, 0xb6, 0x96, 0x99, 0xde, 0x09, 0x53, 0xde, 0x38, 0x8b,
	0xea, 0x7c, 0x0b, 0xb0, 0x76, 0xb2, 0xd5, 0xbd, 0x37, 0x97, 0x0b, 0x79, 0xb4, 0x1b, 0x35, 0xf1,
	0x9f, 0x5a, 0x77, 0x4e, 0x6d, 0xf7, 0x57, 0xed, 0x59, 0xd6, 0xe3, 0x3e, 0xfc, 0x06, 0x00, 0x00,
	0xff, 0xff, 0xd8, 0x8e, 0xef, 0xec, 0x6d, 0x01, 0x00, 0x00,
}
